apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-game-quagga
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "454264311290"
    provider: eks
    region: eu-west-2
    registry: 454264311290.dkr.ecr.eu-west-2.amazonaws.com
  environments:
  - key: dev
    owner: jenkinx3demo
    repository: demojenkinsx3-cluster
  - key: staging
  - key: production
  ingress:
    domain: 18.170.12.85.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: sazalbot
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-tf-jx-game-quagga-20210727061937793600000008
  - name: reports
    url: s3://reports-tf-jx-game-quagga-20210727061937792500000006
  - name: repository
    url: s3://repository-tf-jx-game-quagga-20210727061937792100000005
  terraform: true
  vault:
    aws:
      dynamoDBRegion: eu-west-2
      dynamoDBTable: vault-unseal-tf-jx-game-quagga-C1Iqmbfl
      kmsKeyId: dbb4e79b-1aac-45e2-bf86-80db3c7e30b5
      kmsRegion: eu-west-2
      s3Bucket: vault-unseal-tf-jx-game-quagga-20210727061937793000000007
      s3Region: eu-west-2
  webhook: lighthouse
