filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://chartmuseum-jx.18.170.12.85.nip.io/
releases:
- chart: dev/jx3-springboot-demo
  version: 0.0.1
  name: jx3-springboot-demo
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
